blogapp/config/routes.rb
Rails.application.routes.draw do
devise_for :users

  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :show, :create]

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blogapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blogapp/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

blogapp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
end

blogapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blogapp/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def index
    @posts = Post.all
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    
    if @post.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
    
  end

  private
  def post_params
    params.require(:post).permit(:content)
  end
  
end

blogapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

blogapp/app/helpers/application_helper.rb
module ApplicationHelper
end

blogapp/app/helpers/posts_helper.rb
module PostsHelper
end

blogapp/app/helpers/users_helper.rb
module UsersHelper
end

blogapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>DeviseRails5</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <header>
            <nav>
                <% if user_signed_in? %>
                <strong><%= link_to current_user.email, posts_path %></strong>
                <%= link_to 'プロフィール変更', edit_user_registration_path %>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
            <% else %>
                <%= link_to 'サインアップ', new_user_registration_path %>
                <%= link_to 'ログイン', new_user_session_path %>
                <% end %>
            </nav>
        </header>

        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <%= yield %>
    </body>
</html>

blogapp/app/views/posts/index.html.erb
<h1>index.html.erb</h1>
<% if user_signed_in? %>
    <h2>投稿する</h2>
  <%= form_for @post do |f| %>
    <%= f.text_field :content %>
    <%= f.submit %>
  <% end %>
  <div id="main">
    <img src="main-img.jpg">
</div>


<div id="article_wrap">

    <div id="article_list">
        
  
  
  <hr>
  <% @posts.each do |post| %>
  <div>
    <h2><a href="/posts/<%= post.id %>"><%= post.content %></a></h2>
    <p><a href="/users/<%= post.user.id %>"><%= post.user.email %></a></p>
    
  <% end %>

<% else %>
  <%= link_to "ユーザー登録", new_user_registration_path %>
  <%= link_to "ログイン", new_user_session_path %>
<% end %>



        

    </div>

    <div id="sidebar">
        
        <h2>★PV数ランキング</h2>
        <ul>
            <li><a href="">記事タイトル記事タイトル１記事タイトル記事タイトル<span>（10PV）</span></a></li>
            <li><a href="">記事タイトル記事タイトル１記事タイトル記事タイトル<span>（8PV）</span></a></li>
            <li><a href="">記事タイトル記事タイトル１記事タイトル記事タイトル<span>（2PV）</span></a></li>
        </ul>
    </div>
    <div class="clear"></div>
</div>

blogapp/app/views/posts/show.html.erb
<h1>投稿詳細ページ</h1>
<h3><%= @post.user.email %></h3>
<h3><%= @post.content %></h3>
<%= link_to "ホームへ戻る", posts_path %>

blogapp/app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<% @users.each do |user| %>
  <a href="/users/<%= user.id %>"><%= user.email %></a>
  <hr>
<% end %>
<%= link_to "ホームへ戻る", posts_path %>

blogapp/app/views/users/show.html.erb
<h1>show.html.erb</h1>
<h3><%= @user.email %></h3>
<h2>ブログの中身</h2>
<% @user.posts.each do |post| %>
<div id="title">
    <div>
  <h1><a href="/posts/<%= post.id %>"><%= post.content %></a></h1>
    </div>
</div>
  <hr>
<% end %>
<%= link_to "ユーザー一覧へ", users_path %>
<%= link_to "ホームへ戻る", posts_path %>



    <div id="sidebar">
        
        <h2>★PV数ランキング</h2>
        <ul>
            <li><a href="">記事タイトル記事タイトル１記事タイトル記事タイトル<span>（10PV）</span></a></li>
            <li><a href="">記事タイトル記事タイトル１記事タイトル記事タイトル<span>（8PV）</span></a></li>
            <li><a href="">記事タイトル記事タイトル１記事タイトル記事タイトル<span>（2PV）</span></a></li>
        </ul>
    </div>
    <div class="clear"></div>
</div>